packages:
  - 'packages/*'
catalog:
  '@antfu/eslint-config': ^4.13.0
  '@types/node': ^22.15.17
  '@vitest/eslint-plugin': ^1.1.44
  '@vue/compiler-sfc': ^3.5.13
  chalk: ^5.4.1
  changelogen: ^0.6.1
  commander: ^13.1.0
  eslint: ^9.26.0
  oxc-parser: ^0.67.0
  taze: ^19.1.0
  tinyglobby: ^0.2.13
  typescript: ^5.8.3
  unbuild: ^3.5.0
  vitest: ^3.1.3
